// <auto-generated/>
namespace RuntimeFlow.Contexts.Generated
{
    internal static class CompiledInitializationGraph
    {
        internal const string RuleVersion = "";

        internal sealed class Node
        {
            internal Node(global::System.Type serviceType, global::System.Type implementationType, global::RuntimeFlow.Contexts.GameContextType scope, global::System.Type[] dependencies)
            {
                ServiceType = serviceType;
                ImplementationType = implementationType;
                Scope = scope;
                Dependencies = dependencies;
            }

            internal global::System.Type ServiceType { get; }
            internal global::System.Type ImplementationType { get; }
            internal global::RuntimeFlow.Contexts.GameContextType Scope { get; }
            internal global::System.Type[] Dependencies { get; }
        }

        internal static readonly Node[] Nodes = new Node[]
        {
        };
    }
}
