using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace RuntimeFlow.Generators
{
    public sealed partial class InitializationGraphGenerator
    {
        private static string Render(GenerationModel model)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace RuntimeFlow.Contexts.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class CompiledInitializationGraph");
            sb.AppendLine("    {");
            sb.AppendLine($"        internal const string RuleVersion = \"{GraphRulesVersion}\";");
            sb.AppendLine();
            sb.AppendLine("        internal sealed class Node");
            sb.AppendLine("        {");
            sb.AppendLine("            internal Node(global::System.Type serviceType, global::System.Type implementationType, global::RuntimeFlow.Contexts.GameContextType scope, global::System.Type[] dependencies)");
            sb.AppendLine("            {");
            sb.AppendLine("                ServiceType = serviceType;");
            sb.AppendLine("                ImplementationType = implementationType;");
            sb.AppendLine("                Scope = scope;");
            sb.AppendLine("                Dependencies = dependencies;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            internal global::System.Type ServiceType { get; }");
            sb.AppendLine("            internal global::System.Type ImplementationType { get; }");
            sb.AppendLine("            internal global::RuntimeFlow.Contexts.GameContextType Scope { get; }");
            sb.AppendLine("            internal global::System.Type[] Dependencies { get; }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        internal static readonly Node[] Nodes = new Node[]");
            sb.AppendLine("        {");

            foreach (var node in model.Nodes)
            {
                var dependencies = node.Dependencies
                    .Select(dependency => $"typeof({ToTypeOfDisplay(dependency)})")
                    .ToArray();

                sb.Append("            new Node(");
                sb.Append($"typeof({ToTypeOfDisplay(node.ServiceType)}), ");
                sb.Append($"typeof({ToTypeOfDisplay(node.ImplementationType)}), ");
                sb.Append($"global::RuntimeFlow.Contexts.GameContextType.{node.Scope}, ");
                sb.Append($"new global::System.Type[] {{ {string.Join(", ", dependencies)} }}");
                sb.AppendLine("),");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ToTypeOfDisplay(INamedTypeSymbol symbol)
        {
            return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }
    }
}
